# This is a basic workflow to help you get started with Actions

name: AUTO-MESSAGE

# Controls when the workflow will run
on:
  schedule:
    # Action vai rodar a meia noite (min hora diaMes mes diaSemana)
    - cron: '0 0 * * *'

  # workflow_dispatch serve para poder rodar o action manualmente também
  workflow_dispatch:

# um workflow roda em um ou mais jobs que podem rodar sequencialmente ou paralelamente
jobs:
  # build é para dizer onde que os comandos vão ser rodados
  build:
    # nesse exemplo o build é rodado no ubuntu
    runs-on: ubuntu-latest

    # Steps são as tarefas que vão ser feitas nesse job
    steps:
      # uses nesse exemplo utiliza o checkout para lidar com checkouts
      - uses: actions/checkout@v3
      
      # Mandando mensagem a meia noite
      - name: Mensagem Boas vindas
        run: echo 'Essa mensagem aconteceu a meia noite'
      
