# This is a basic workflow to help you get started with Actions

name: DAY-VERIFIER

# Controls when the workflow will run
on:
  schedule:
    # Action vai rodar a meia noite (min hora diaMes mes diaSemana)
    - cron: '0 0 * * *'

  # workflow_dispatch serve para poder rodar o action manualmente também
  workflow_dispatch:

# um workflow roda em um ou mais jobs que podem rodar sequencialmente ou paralelamente
jobs:
  # build é para dizer onde que os comandos vão ser rodados
  build:
    # nesse exemplo o build é rodado no ubuntu
    runs-on: ubuntu-latest

    # Steps são as tarefas que vão ser feitas nesse job
    steps:
      
      # Mandando mensagem a meia noite no arquivo datas_backup.txt
      - name: Pegando a data atual
        run: |
          echo 'Data atual e hora atual do workflow' > datas_backup.txt
          date '+%d/%m/%Y %H:%M:%S' > datas_backup.txt
      
      # Criando o commit
       # uses nesse exemplo cria um commit com as mudanças
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Atualizado arquivo datas_backup.txt
          
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
          
      
