# This is a basic workflow to help you get started with Actions

name: DAY-VERIFIER

# Controls when the workflow will run
on:
  schedule:
    # Action vai rodar a meia noite (min hora diaMes mes diaSemana)
    - cron: '0 0 * * *'

  # workflow_dispatch serve para poder rodar o action manualmente também
  workflow_dispatch:

# um workflow roda em um ou mais jobs que podem rodar sequencialmente ou paralelamente
jobs:
  # build é para dizer onde que os comandos vão ser rodados
  build:
    # nesse exemplo o build é rodado no ubuntu
    runs-on: ubuntu-latest

    # Steps são as tarefas que vão ser feitas nesse job
    steps:
    
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      # Baixando o node.js
      - name: Baixando o node.js por comando
        run: sudo apt-get install nodejs
      
      # Baixando o NPM
      - name: Baixando o npm por comando
        run: auso apt-get install npm
        
      # Baixando o coinmon
      - name: Baixando o coinmon
        run: sudo npm install -g coinmon
        
      # Enviando os dados do coinmon para o arquivo
      - name: Enviando dados do coinmon para o arquivo
        run: |
            echo '-------------------------------------------------------------------------' >> datas_backup.txt
            echo ' ' >> datas_backup.txt
            coinmon >> datas_backup.txt
            echo ' ' >> datas_backup.txt
      
        
      # Avisando que as infos foram salvas
      - name: Adicionando que foi confirmado
        run: echo '✔️ Workflow rodado com sucesso a meia noite!' >> datas_backup.txt
          
      # Criando um commit
      - name: Criando um commit
        run: |
          git status
          git config user.email "gabriel.stundner@acad.pucrs.br"
          git config user.name "F4NT0"
          git add ./datas_backup.txt
          git commit -m "Teste de workflow"
      
      # Fazendo push pelo actions
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.TOKEN}}
          force: true
          
      
          
      
